name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Build Site
        run: |
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          BRANCH: gh-pages
          FOLDER: public
          single-commit: true
